title: Sayan Goswami - Teaching Materials
description: A repo for my teaching materials!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template